# Generated by Django 2.2.17 on 2021-03-26 13:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_auto_20210322_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('SERVICE', 'free'), ('PRODUCT', 'bronze'), ('REVERSE_PAYMENT', 'reverse_payment')], default='', max_length=50)),
                ('value', models.IntegerField(default=0)),
                ('method', models.CharField(choices=[('CASH', 'cash'), ('ORANGE_MONEY', 'orange_money'), ('MOMO', 'momo'), ('VISA', 'visa'), ('MASTERCARD', 'mastercard')], default='', max_length=50)),
                ('bayed', models.CharField(default='AYD_ACCOUNT', max_length=50)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile')),
            ],
        ),
    ]
