# Generated by Django 2.2.17 on 2021-03-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_paymentoperation_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentoperation',
            name='purpose',
            field=models.CharField(choices=[('SERVICE', 'service'), ('PRODUCT', 'product'), ('REVERSE_PAYMENT', 'reverse_payment')], default='', max_length=50),
        ),
    ]
