# Generated by Django 2.0 on 2020-12-11 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20201211_1659'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='coretrackedmodel_ptr',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
