# Generated by Django 2.2.17 on 2021-03-26 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mybox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxSubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FREE', 'free'), ('BRONZE', 'bronze'), ('SILVER', 'silver'), ('GOLD', 'gold')], default='FREE', max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
