# Generated by Django 2.2.17 on 2021-03-26 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210322_1218'),
        ('mybox', '0002_boxsubscriptionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxsubscriptionplan',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile'),
        ),
    ]
