# Generated by Django 2.2.17 on 2021-03-27 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybox', '0003_boxsubscriptionplan_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxsubscriptionplan',
            name='subscriber',
        ),
    ]
