# Generated by Django 2.2.17 on 2021-03-27 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mybox', '0004_remove_boxsubscriptionplan_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxsubscriptionplan',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boxsubscriptionplan',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
