# Generated by Django 2.0 on 2020-12-11 13:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import editorial.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('author', models.CharField(max_length=250)),
                ('guess', models.CharField(max_length=150)),
                ('photograph', models.CharField(max_length=150)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('resume', models.TextField()),
                ('content', models.TextField()),
                ('facebookUrl', models.TextField(blank=True, null=True)),
                ('twitterUrl', models.TextField(blank=True, null=True)),
                ('whatsappUrl', models.TextField(blank=True, null=True)),
                ('mailUrl', models.TextField(blank=True, null=True)),
                ('coverImage', models.FileField(blank=True, null=True, upload_to=editorial.models.articles_image_path)),
                ('articleImage', models.FileField(blank=True, null=True, upload_to=editorial.models.articles_image_path)),
                ('cover', models.BooleanField(default=False)),
                ('mainMenu', models.BooleanField(default=False)),
                ('is_home', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.UserProfile')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.UserProfile')),
            ],
        ),
    ]
